nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
edad = int(input("Ingrese su edad"))
ciudad = input("Ingrese su ciudad: ")
universidad = input("Ingrese su universidad: ")
carrera = input("Ingrese su carrera: ")
semestre = int(input("Ingrese su semestre: "))
promedio = float(input("ingrese su promedio: "))

print("=========== PERFIL DEL ESTUDIANTE ===========")
print("Nombre completo:", nombre, apellido)
print("edad:", edad)
print("Ciudad:", ciudad)
print("Universidad:", universidad)
print("Carrera:", carrera)
print("Semestre:", semestre)
print("promedio:", promedio)
print("===============================================")
